# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='soap.proto',
  package='restproto',
  syntax='proto3',
  serialized_pb=_b('\n\nsoap.proto\x12\trestproto\"1\n\x06RegReq\x12\x0b\n\x03uId\x18\x01 \x01(\t\x12\r\n\x05uName\x18\x02 \x01(\t\x12\x0b\n\x03pwd\x18\x03 \x01(\t\"\x15\n\x06RegRsp\x12\x0b\n\x03ret\x18\x01 \x01(\x05\"$\n\x08LoginReq\x12\x0b\n\x03uId\x18\x01 \x01(\t\x12\x0b\n\x03pwd\x18\x02 \x01(\t\"?\n\x05uInfo\x12\x0b\n\x03uId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0e\n\x06gender\x18\x04 \x01(\x05\" \n\x04lCfg\x12\x0b\n\x03sip\x18\x01 \x01(\t\x12\x0b\n\x03hit\x18\x02 \x01(\x05\"\x88\x01\n\x08LoginRsp\x12\x0b\n\x03ret\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t\x12\x1d\n\x04lcfg\x18\x03 \x01(\x0b\x32\x0f.restproto.lCfg\x12\x1e\n\x04host\x18\x04 \x01(\x0b\x32\x10.restproto.uInfo\x12!\n\x07\x66riends\x18\x05 \x03(\x0b\x32\x10.restproto.uInfo\"\x1a\n\tLogoutReq\x12\r\n\x05token\x18\x01 \x01(\t\"\x18\n\tLogoutRsp\x12\x0b\n\x03ret\x18\x01 \x01(\x05\"\x98\x02\n\x03Msg\x1a\x96\x01\n\x0b\x63ontentInfo\x12\r\n\x05msgId\x18\x01 \x01(\t\x12\x31\n\x03mct\x18\x02 \x01(\x0e\x32$.restproto.Msg.contentInfo.msgCtType\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"4\n\tmsgCtType\x12\x08\n\x04text\x10\x00\x12\x07\n\x03pic\x10\x01\x12\t\n\x05\x61udio\x10\x02\x12\t\n\x05video\x10\x03\x1ax\n\trouteInfo\x12.\n\x02rt\x18\x01 \x01(\x0e\x32\".restproto.Msg.routeInfo.routeType\x12\r\n\x05srcId\x18\x02 \x01(\t\x12\r\n\x05\x64stId\x18\x03 \x01(\t\"\x1d\n\trouteType\x12\x07\n\x03p2p\x10\x00\x12\x07\n\x03p2g\x10\x01\"<\n\x11KeepAliveLoginReq\x12\r\n\x05token\x18\x01 \x01(\t\x1a\x18\n\tloginInfo\x12\x0b\n\x03\x63ip\x18\x01 \x01(\t\"A\n\x11KeepAliveLoginRsp\x12\x0b\n\x03ret\x18\x01 \x01(\x05\x12\x1f\n\x07msgList\x18\x02 \x03(\x0b\x32\x0e.restproto.Msg\"\"\n\x06MsgRsp\x12\x0b\n\x03ret\x18\x01 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\t\"\x08\n\x06rpcRsp2B\n\x0fRouteMsgService\x12/\n\x08RouteMsg\x12\x0e.restproto.Msg\x1a\x11.restproto.rpcRsp\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MSG_CONTENTINFO_MSGCTTYPE = _descriptor.EnumDescriptor(
  name='msgCtType',
  full_name='restproto.Msg.contentInfo.msgCtType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='text', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pic', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='audio', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='video', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=536,
  serialized_end=588,
)
_sym_db.RegisterEnumDescriptor(_MSG_CONTENTINFO_MSGCTTYPE)

_MSG_ROUTEINFO_ROUTETYPE = _descriptor.EnumDescriptor(
  name='routeType',
  full_name='restproto.Msg.routeInfo.routeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='p2p', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='p2g', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=681,
  serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_MSG_ROUTEINFO_ROUTETYPE)


_REGREQ = _descriptor.Descriptor(
  name='RegReq',
  full_name='restproto.RegReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uId', full_name='restproto.RegReq.uId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uName', full_name='restproto.RegReq.uName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pwd', full_name='restproto.RegReq.pwd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=74,
)


_REGRSP = _descriptor.Descriptor(
  name='RegRsp',
  full_name='restproto.RegRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='restproto.RegRsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=97,
)


_LOGINREQ = _descriptor.Descriptor(
  name='LoginReq',
  full_name='restproto.LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uId', full_name='restproto.LoginReq.uId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pwd', full_name='restproto.LoginReq.pwd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=135,
)


_UINFO = _descriptor.Descriptor(
  name='uInfo',
  full_name='restproto.uInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uId', full_name='restproto.uInfo.uId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='restproto.uInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='restproto.uInfo.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='restproto.uInfo.gender', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=200,
)


_LCFG = _descriptor.Descriptor(
  name='lCfg',
  full_name='restproto.lCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sip', full_name='restproto.lCfg.sip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hit', full_name='restproto.lCfg.hit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=234,
)


_LOGINRSP = _descriptor.Descriptor(
  name='LoginRsp',
  full_name='restproto.LoginRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='restproto.LoginRsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='restproto.LoginRsp.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lcfg', full_name='restproto.LoginRsp.lcfg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='restproto.LoginRsp.host', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friends', full_name='restproto.LoginRsp.friends', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=373,
)


_LOGOUTREQ = _descriptor.Descriptor(
  name='LogoutReq',
  full_name='restproto.LogoutReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='restproto.LogoutReq.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=401,
)


_LOGOUTRSP = _descriptor.Descriptor(
  name='LogoutRsp',
  full_name='restproto.LogoutRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='restproto.LogoutRsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=427,
)


_MSG_CONTENTINFO = _descriptor.Descriptor(
  name='contentInfo',
  full_name='restproto.Msg.contentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgId', full_name='restproto.Msg.contentInfo.msgId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mct', full_name='restproto.Msg.contentInfo.mct', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='restproto.Msg.contentInfo.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSG_CONTENTINFO_MSGCTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=588,
)

_MSG_ROUTEINFO = _descriptor.Descriptor(
  name='routeInfo',
  full_name='restproto.Msg.routeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rt', full_name='restproto.Msg.routeInfo.rt', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srcId', full_name='restproto.Msg.routeInfo.srcId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dstId', full_name='restproto.Msg.routeInfo.dstId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSG_ROUTEINFO_ROUTETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=590,
  serialized_end=710,
)

_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='restproto.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_MSG_CONTENTINFO, _MSG_ROUTEINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=710,
)


_KEEPALIVELOGINREQ_LOGININFO = _descriptor.Descriptor(
  name='loginInfo',
  full_name='restproto.KeepAliveLoginReq.loginInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cip', full_name='restproto.KeepAliveLoginReq.loginInfo.cip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=748,
  serialized_end=772,
)

_KEEPALIVELOGINREQ = _descriptor.Descriptor(
  name='KeepAliveLoginReq',
  full_name='restproto.KeepAliveLoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='restproto.KeepAliveLoginReq.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_KEEPALIVELOGINREQ_LOGININFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=772,
)


_KEEPALIVELOGINRSP = _descriptor.Descriptor(
  name='KeepAliveLoginRsp',
  full_name='restproto.KeepAliveLoginRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='restproto.KeepAliveLoginRsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgList', full_name='restproto.KeepAliveLoginRsp.msgList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=774,
  serialized_end=839,
)


_MSGRSP = _descriptor.Descriptor(
  name='MsgRsp',
  full_name='restproto.MsgRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='restproto.MsgRsp.ret', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='restproto.MsgRsp.ack', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=841,
  serialized_end=875,
)


_RPCRSP = _descriptor.Descriptor(
  name='rpcRsp',
  full_name='restproto.rpcRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=877,
  serialized_end=885,
)

_LOGINRSP.fields_by_name['lcfg'].message_type = _LCFG
_LOGINRSP.fields_by_name['host'].message_type = _UINFO
_LOGINRSP.fields_by_name['friends'].message_type = _UINFO
_MSG_CONTENTINFO.fields_by_name['mct'].enum_type = _MSG_CONTENTINFO_MSGCTTYPE
_MSG_CONTENTINFO.containing_type = _MSG
_MSG_CONTENTINFO_MSGCTTYPE.containing_type = _MSG_CONTENTINFO
_MSG_ROUTEINFO.fields_by_name['rt'].enum_type = _MSG_ROUTEINFO_ROUTETYPE
_MSG_ROUTEINFO.containing_type = _MSG
_MSG_ROUTEINFO_ROUTETYPE.containing_type = _MSG_ROUTEINFO
_KEEPALIVELOGINREQ_LOGININFO.containing_type = _KEEPALIVELOGINREQ
_KEEPALIVELOGINRSP.fields_by_name['msgList'].message_type = _MSG
DESCRIPTOR.message_types_by_name['RegReq'] = _REGREQ
DESCRIPTOR.message_types_by_name['RegRsp'] = _REGRSP
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['uInfo'] = _UINFO
DESCRIPTOR.message_types_by_name['lCfg'] = _LCFG
DESCRIPTOR.message_types_by_name['LoginRsp'] = _LOGINRSP
DESCRIPTOR.message_types_by_name['LogoutReq'] = _LOGOUTREQ
DESCRIPTOR.message_types_by_name['LogoutRsp'] = _LOGOUTRSP
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['KeepAliveLoginReq'] = _KEEPALIVELOGINREQ
DESCRIPTOR.message_types_by_name['KeepAliveLoginRsp'] = _KEEPALIVELOGINRSP
DESCRIPTOR.message_types_by_name['MsgRsp'] = _MSGRSP
DESCRIPTOR.message_types_by_name['rpcRsp'] = _RPCRSP

RegReq = _reflection.GeneratedProtocolMessageType('RegReq', (_message.Message,), dict(
  DESCRIPTOR = _REGREQ,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.RegReq)
  ))
_sym_db.RegisterMessage(RegReq)

RegRsp = _reflection.GeneratedProtocolMessageType('RegRsp', (_message.Message,), dict(
  DESCRIPTOR = _REGRSP,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.RegRsp)
  ))
_sym_db.RegisterMessage(RegRsp)

LoginReq = _reflection.GeneratedProtocolMessageType('LoginReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQ,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.LoginReq)
  ))
_sym_db.RegisterMessage(LoginReq)

uInfo = _reflection.GeneratedProtocolMessageType('uInfo', (_message.Message,), dict(
  DESCRIPTOR = _UINFO,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.uInfo)
  ))
_sym_db.RegisterMessage(uInfo)

lCfg = _reflection.GeneratedProtocolMessageType('lCfg', (_message.Message,), dict(
  DESCRIPTOR = _LCFG,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.lCfg)
  ))
_sym_db.RegisterMessage(lCfg)

LoginRsp = _reflection.GeneratedProtocolMessageType('LoginRsp', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRSP,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.LoginRsp)
  ))
_sym_db.RegisterMessage(LoginRsp)

LogoutReq = _reflection.GeneratedProtocolMessageType('LogoutReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTREQ,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.LogoutReq)
  ))
_sym_db.RegisterMessage(LogoutReq)

LogoutRsp = _reflection.GeneratedProtocolMessageType('LogoutRsp', (_message.Message,), dict(
  DESCRIPTOR = _LOGOUTRSP,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.LogoutRsp)
  ))
_sym_db.RegisterMessage(LogoutRsp)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(

  contentInfo = _reflection.GeneratedProtocolMessageType('contentInfo', (_message.Message,), dict(
    DESCRIPTOR = _MSG_CONTENTINFO,
    __module__ = 'soap_pb2'
    # @@protoc_insertion_point(class_scope:restproto.Msg.contentInfo)
    ))
  ,

  routeInfo = _reflection.GeneratedProtocolMessageType('routeInfo', (_message.Message,), dict(
    DESCRIPTOR = _MSG_ROUTEINFO,
    __module__ = 'soap_pb2'
    # @@protoc_insertion_point(class_scope:restproto.Msg.routeInfo)
    ))
  ,
  DESCRIPTOR = _MSG,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.Msg)
  ))
_sym_db.RegisterMessage(Msg)
_sym_db.RegisterMessage(Msg.contentInfo)
_sym_db.RegisterMessage(Msg.routeInfo)

KeepAliveLoginReq = _reflection.GeneratedProtocolMessageType('KeepAliveLoginReq', (_message.Message,), dict(

  loginInfo = _reflection.GeneratedProtocolMessageType('loginInfo', (_message.Message,), dict(
    DESCRIPTOR = _KEEPALIVELOGINREQ_LOGININFO,
    __module__ = 'soap_pb2'
    # @@protoc_insertion_point(class_scope:restproto.KeepAliveLoginReq.loginInfo)
    ))
  ,
  DESCRIPTOR = _KEEPALIVELOGINREQ,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.KeepAliveLoginReq)
  ))
_sym_db.RegisterMessage(KeepAliveLoginReq)
_sym_db.RegisterMessage(KeepAliveLoginReq.loginInfo)

KeepAliveLoginRsp = _reflection.GeneratedProtocolMessageType('KeepAliveLoginRsp', (_message.Message,), dict(
  DESCRIPTOR = _KEEPALIVELOGINRSP,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.KeepAliveLoginRsp)
  ))
_sym_db.RegisterMessage(KeepAliveLoginRsp)

MsgRsp = _reflection.GeneratedProtocolMessageType('MsgRsp', (_message.Message,), dict(
  DESCRIPTOR = _MSGRSP,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.MsgRsp)
  ))
_sym_db.RegisterMessage(MsgRsp)

rpcRsp = _reflection.GeneratedProtocolMessageType('rpcRsp', (_message.Message,), dict(
  DESCRIPTOR = _RPCRSP,
  __module__ = 'soap_pb2'
  # @@protoc_insertion_point(class_scope:restproto.rpcRsp)
  ))
_sym_db.RegisterMessage(rpcRsp)


# @@protoc_insertion_point(module_scope)
